name: automate
description: "The one-stop shop for automotive services."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  cloud_firestore: ^4.17.3
  provider: ^6.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/AutoMate.png
  uses-material-design: true
  
  

