name: automate
description: "The one-stop shop for automotive services."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  cloud_firestore: ^4.17.3
  provider: ^6.1.2
  shared_preferences: ^2.0.8
  google_maps_flutter: ^2.0.6
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  google_maps_flutter_platform_interface: ^2.6.0
  google_maps_flutter_android: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/AutoMate.png
    - assets/placeholder.jpg
    - assets/placeholder_1.jpg
    - assets/repair_shop.jpg
    - assets/detailing_shop.jpg
    - assets/tyre_shop.jpg
    - assets/tyre_shop2.jpg
    - assets/tyre_shop3.jpg
    - assets/workshops.json
    - assets/repair_shop2.jpg
    - assets/repair_shop3.jpg
    - assets/detailing_shop2.jpg
    - assets/detailing_shop3.png
    - assets/
  uses-material-design: true
  
  

